# Generated by Django 6.0.6 on 2026-06-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add_menu', models.BooleanField(default=False)),
                ('can_edit_menu', models.BooleanField(default=False)),
                ('can_delete_menu', models.BooleanField(default=False)),
                ('can_add_table', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Waiter Permissions',
            },
        ),
    ]
