# Generated by Django 6.0.6 on 2026-06-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
