# Generated by Django 6.0.6 on 2026-07-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='daily_order_number',
            field=models.IntegerField(default=0),
        ),
    ]
