# Generated by Django 6.0.6 on 2026-07-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_daily_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('na', 'N/A')], default='na', max_length=10),
        ),
    ]
